
--#creacion de tablas
--drop table chupi_recetas.INGREDIENTE_RECETA_MEDIDA;
--drop table chupi_recetas.TIPO_INGREDIENTE;
--drop table chupi_recetas.UNIDAD_MEDIDA;
--drop table chupi_recetas.RECETA_TAG;
--drop table chupi_recetas.MENU_RECETA_POSICION;
--drop table chupi_recetas.PLANIFICACION_MENU;
--drop table chupi_recetas.PASO;
--drop table chupi_recetas.POSICION;
--drop table chupi_recetas.INGREDIENTE;
--drop table chupi_recetas.TAG;
--drop table chupi_recetas.PLANIFICACION;
--drop table chupi_recetas.MENU;
--drop table chupi_recetas.RECETA;


create schema chupi_recetas;

create table chupi_recetas.TIPO_INGREDIENTE(
	FECHA_CREACION TIMESTAMP NOT NULL,
	FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_ACTUALIZACION VARCHAR(50) NOT NULL,
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50),
	PRIMARY KEY(ID)
);



create table chupi_recetas.INGREDIENTE(
	FECHA_CREACION TIMESTAMP NOT NULL,
	FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_ACTUALIZACION VARCHAR(50) NOT NULL,
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50),
	TIPO_INGREDIENTE_ID INTEGER,
	PRIMARY KEY(ID)
);



create table chupi_recetas.UNIDAD_MEDIDA(
	FECHA_CREACION TIMESTAMP NOT NULL,
	FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_ACTUALIZACION VARCHAR(50) NOT NULL,
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID)
);

create table chupi_recetas.RECETA(
	FECHA_CREACION TIMESTAMP NOT NULL,
	FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_ACTUALIZACION VARCHAR(50) NOT NULL,
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(100) NOT NULL,
	CALORIAS DECIMAL(5,2),
	IMAGEN VARCHAR(500),
	PRIMARY KEY(ID)

);

create table chupi_recetas.INGREDIENTE_RECETA_MEDIDA(
	FECHA_CREACION TIMESTAMP NOT NULL,
	FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_ACTUALIZACION VARCHAR(50) NOT NULL,
	INGREDIENTE_ID INTEGER NOT NULL,
	RECETA_ID INTEGER NOT NULL,
	UNIDAD_MEDIDA_ID INTEGER NOT NULL,
	CANTIDAD DECIMAL(3,2) NOT NULL,
	PRIMARY KEY (INGREDIENTE_ID,RECETA_ID,UNIDAD_MEDIDA_ID)
);

create table chupi_recetas.TAG(
	FECHA_CREACION TIMESTAMP NOT NULL,
	FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_ACTUALIZACION VARCHAR(50) NOT NULL,
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID)
);

create table chupi_recetas.RECETA_TAG(
	FECHA_CREACION TIMESTAMP NOT NULL,
	FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_ACTUALIZACION VARCHAR(50) NOT NULL,
	RECETA_ID INTEGER NOT NULL,
	TAG_ID INTEGER NOT NULL,
	PRIMARY KEY (RECETA_ID,TAG_ID)
);

create table chupi_recetas.PASO(
	FECHA_CREACION TIMESTAMP NOT NULL,
	FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_ACTUALIZACION VARCHAR(50) NOT NULL,
	ID INTEGER NOT NULL AUTO_INCREMENT,
	DESCRIPCION VARCHAR(2000) NOT NULL,
	RECETA_ID INTEGER NOT NULL,
	PRIMARY KEY(ID)
);

create table chupi_recetas.MENU(
	FECHA_CREACION TIMESTAMP NOT NULL,
	FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_ACTUALIZACION VARCHAR(50) NOT NULL,
	ID INTEGER NOT NULL AUTO_INCREMENT,
	DESCRIPCION VARCHAR(2000) NOT NULL,
	PRIMARY KEY(ID)
);

create table chupi_recetas.POSICION_PLATO(
	FECHA_CREACION TIMESTAMP NOT NULL,
	FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_ACTUALIZACION VARCHAR(50) NOT NULL,
	ID INTEGER NOT NULL AUTO_INCREMENT,
	DESCRIPCION VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID)
);

create table chupi_recetas.MENU_RECETA_POSICION(
	FECHA_CREACION TIMESTAMP NOT NULL,
	FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_ACTUALIZACION VARCHAR(50) NOT NULL,
	POSICION_PLATO_ID INTEGER NOT NULL,
	RECETA_ID INTEGER NOT NULL,
	MENU_ID INTEGER NOT NULL,

	PRIMARY KEY(MENU_ID,RECETA_ID,POSICION_PLATO_ID)

);

create table chupi_recetas.PLANIFICACION(
	FECHA_CREACION TIMESTAMP NOT NULL,
	FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_ACTUALIZACION VARCHAR(50) NOT NULL,
	ID INTEGER NOT NULL AUTO_INCREMENT,
	FECHA_INI DATE,
	FECHA_FIN DATE,
	PRIMARY KEY(ID)
);

create table chupi_recetas.PLANIFICACION_MENU(
	FECHA_CREACION TIMESTAMP NOT NULL,
	FECHA_ACTUALIZACION TIMESTAMP NOT NULL,
	USUARIO_CREACION VARCHAR(50) NOT NULL,
	USUARIO_ACTUALIZACION VARCHAR(50) NOT NULL,
	PLANIFICACION_ID INTEGER NOT NULL,
	MENU_ID INTEGER NOT NULL,
	FECHA DATE,
	PRIMARY KEY(PLANIFICACION_ID,MENU_ID)
);


--#Creacion de las claves foraneas
ALTER TABLE chupi_recetas.INGREDIENTE ADD FOREIGN KEY ( TIPO_INGREDIENTE_ID ) REFERENCES TIPO_INGREDIENTE( ID ) ;
ALTER TABLE chupi_recetas.INGREDIENTE_RECETA_MEDIDA ADD FOREIGN KEY ( INGREDIENTE_ID ) REFERENCES INGREDIENTE( ID ) ;
ALTER TABLE chupi_recetas.INGREDIENTE_RECETA_MEDIDA ADD FOREIGN KEY ( RECETA_ID ) REFERENCES RECETA( ID ) ;
ALTER TABLE chupi_recetas.INGREDIENTE_RECETA_MEDIDA ADD FOREIGN KEY ( UNIDAD_MEDIDA_ID ) REFERENCES UNIDAD_MEDIDA( ID ) ;
ALTER TABLE chupi_recetas.RECETA_TAG ADD FOREIGN KEY ( RECETA_ID ) REFERENCES RECETA( ID ) ;
ALTER TABLE chupi_recetas.RECETA_TAG ADD FOREIGN KEY ( TAG_ID ) REFERENCES TAG( ID ) ;
ALTER TABLE chupi_recetas.PASO ADD FOREIGN KEY ( RECETA_ID ) REFERENCES RECETA( ID ) ;
ALTER TABLE chupi_recetas.MENU_RECETA_POSICION ADD FOREIGN KEY ( RECETA_ID ) REFERENCES RECETA( ID ) ;
ALTER TABLE chupi_recetas.MENU_RECETA_POSICION ADD FOREIGN KEY ( POSICION_PLATO_ID ) REFERENCES POSICION_PLATO( ID ) ;
ALTER TABLE chupi_recetas.MENU_RECETA_POSICION ADD FOREIGN KEY ( MENU_ID ) REFERENCES MENU( ID ) ;
ALTER TABLE chupi_recetas.PLANIFICACION_MENU ADD FOREIGN KEY ( MENU_ID ) REFERENCES MENU( ID ) ;
ALTER TABLE chupi_recetas.PLANIFICACION_MENU ADD FOREIGN KEY ( PLANIFICACION_ID ) REFERENCES PLANIFICACION( ID ) ;